### ISSUE TITLE
Arch Linux - Failed to launch the browser process! spawn chrome ENOENT

### ISSUE THREAD

**Issue by Lanklow** [davekats/canvas-student-data-export#14]
I'm running this program on Arch Linux, and I get the error: 'Failed to launch the browser process! spawn chrome ENOENT'.

I have tried changing the browser executable path in 'singlefile.py', but it results in the same error.

I will post logs if needed.

**Comment by Lanklow** [comment]
I just realized that I forgot to uncomment line 12.

Sorry for being a dumbass. Thank you for this wonderful tool!

**Comment by supposedly** [comment]
Thank you for posting this to remind other people that might've forgotten to check line 12. Not me though. Just other people
