### ISSUE TITLE
Cannot bypass login page for any downloaded HTML files

### ISSUE THREAD

**Issue by banksmic** [davekats/canvas-student-data-export#16]
I am able to download the module HTML files from Canvas, however all of them just show the login page where you type in your university credentials.  Even the credentials that I know currently work will not work on the local HTML files.

I opened one in Visual Studio Code to see what it looks like, and it seems that everything except the login portion is base64 encoded, and is likely encrypted.  Is there a way around this?

**Comment by davekats** [comment]
@dj346 Are you able to help debug this issue? I no longer have access to Canvas so it's difficult for me to debug issues like this

**Comment by davekats** [comment]
@banksmic Do you have your cookies file set up? 
![image](https://github.com/davekats/canvas-student-data-export/assets/1835097/111a884d-9999-4b5c-b699-dfa2dcc16275)

**Comment by davekats** [comment]
I will close this for now. Let me know if you still have any issues.
