### ISSUE TITLE
ModuleNotFoundError: No module named 'canvasapi'

### ISSUE THREAD

**Issue by raymurt** [davekats/canvas-student-data-export#17]
I'm running this on my Mac. I've already installed canvasapi module to my computer by typing in the terminal:
`pip install canvasapi`

Later on, after having installed everything, I went ahead to run export.py by typing:
`python3 export.py`

Then I was greeted with the following:

```
Traceback (most recent call last):
  File "/Users/raymu/Downloads/canvas-student-data-export-master/export.py", line 7, in <module>
    from canvasapi import Canvas
ModuleNotFoundError: No module named 'canvasapi'
```

**Comment by davekats** [comment]
Hi @raymurt, you might have two different versions of python and pip installed. Try running `pip3 install canvasapi` then `python3 export.py`
