### ISSUE TITLE
Course Files Download but no Modules Content

### ISSUE THREAD

**Issue by KaylaFortson** [davekats/canvas-student-data-export#19]
![image](https://github.com/davekats/canvas-student-data-export/assets/99920941/2f25a9fc-8c8d-4977-a66a-b2bd5ee923e2)

Do you have suggestions for resolving this? Thank you so much for your time!

**Comment by davekats** [comment]
Hi Kayla,

Forbidden errors usually have to do with authorization. Can you view those submissions/modules when you're logged in to Canvas in the browser? If you can view them in the browser but they fail to download using this script, then we should keep investigating. If you want to skip a course that you no longer have permission to access, you can use the `COURSES_TO_SKIP` global variable.

**Comment by KaylaFortson** [comment]
Hello Dave! Thank you for your prompt response. I believe I have permission to view. I think the issue might go a little further than permission view because I have successfully exported all of my courses over the four years and not one single course was able to export the modules section, but course files were successful. Thank you again!

**Comment by davekats** [comment]
Interesting, ok! Are you able to share any more debugging details? Maybe you can add more print statements to help us figure out exactly what is returning this Forbidden message?

**Comment by areisinger** [comment]
i'm having the same issue all the modules which i can see when i log into canvas through a browser are forbidden. I just want the data from the module pages text i'm not really good at python but am willing to be guided

**Comment by davekats** [comment]
@areisinger @KaylaFortson I no longer have access to Canvas so it will be challenging for me to debug this issue. If you'd like you can schedule a call with me and we can debug the issue from your computer: https://usemotion.com/meet/davidk/hxmsj33

**Comment by wdsouza0** [comment]
I'm having the same issue here. I can view and download all of my submissions from the canvas page itself, but it fails when done via the python script.

I also get this error occasionally:
`Skipping file download that gave the following error:
{"status":"unauthorized","errors":[{"message":"user not authorized to perform that action"}]}`

**Comment by asellingson28** [comment]
My friend and I are experiencing the same issue. Any advice on how to proceed would be appreciated!

**Comment by davekats** [comment]
@wdsouza0 @ingensargens Sorry to hear the modules download isn't working. Unfortunately since I no longer have access to Canvas, I can't really reproduce this issue on my machine. If you want to schedule a call, I'd be happy to dig into this with you and debug it from your machine and hopefully we can solve the problem for everyone. You can schedule a call with me here: https://usemotion.com/meet/davidk/hxmsj33

**Comment by tcgm** [comment]
> @wdsouza0 @ingensargens Sorry to hear the modules download isn't working. Unfortunately since I no longer have access to Canvas, I can't really reproduce this issue on my machine. If you want to schedule a call, I'd be happy to dig into this with you and debug it from your machine and hopefully we can solve the problem for everyone. You can schedule a call with me here: [https://usemotion.com/meet/davidk/hxmsj33 ](https://usemotion.com/meet/davidk/hxmsj33)

Did this amount to a fix?

**Comment by conch** [comment]
I had this problem too but was able to fix it - I also had another error about not being able to find Google Chrome, which I'm guessing it uses to actually download the data. I was getting the error that was reported in https://github.com/davekats/canvas-student-data-export/issues/14 and fixed it as described there. After that, my modules folder (and all of the other folders have data in them now. I still get those "forbidden" and "unauthorized" errors, but I believe those are for content types that my instructors didn't use. Everything we did use was able to download.
