### ISSUE TITLE
How do i get this to run on mac?

### ISSUE THREAD

**Issue by Me-Mr** [davekats/canvas-student-data-export#21]
Hi, I've tried to install this on mac but Im not really sure how.  I've installed dependencies.

**Comment by davekats** [comment]
Hi @Me-Mr, do you have experience with Python? Try following the steps outlined in the Getting Started section of the Readme: https://github.com/davekats/canvas-student-data-export#getting-started 
Let me know if you run into any issues.

**Comment by Me-Mr** [comment]
Hi @davekats thank you for your reply! I don't have any experience, but I've set it up. I'm getting this error when installing dependencies: ERROR: Could not find a version that satisfies the requirement python-dateutil==-2.8.2 (from versions: 1.4, 1.4.1, 1.5, 2.1, 2.2, 2.3, 2.4.0, 2.4.1, 2.4.1.post1, 2.4.2, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.8.0, 2.8.1, 2.8.2)
ERROR: No matching distribution found for python-dateutil==-2.8.2

When I install pythondateutil without the version it says it's already installed.

After running export.py I got this error: 

`Traceback (most recent call last):
  File "/Users/a/Downloads/canvas-student-data-export-3/export.py", line 11, in <module>
    from module.download_canvas import download_assignment_pages, download_course_announcement_pages, download_course_discussion_pages, download_course_files, download_course_home_page_html, download_course_html, download_course_module_pages, download_submission_attachments
  File "/Users/a/Downloads/canvas-student-data-export-3/module/download_canvas.py", line 8, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'`

Thank you for your help!

**Comment by Me-Mr** [comment]
Hi I installed the other dependencies on my own. Now I'm getting this error: 

Getting list of all courses...
Fetching Courses...
Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT


TROUBLESHOOTING: https://pptr.dev/troubleshooting

This is where I got stuck before also.

**Comment by davekats** [comment]
@Me-Mr If you want to use singlefile, you will need to edit lines 4 and 12 of the `singlefile.py` file and set the path to the path of your chrome or chromium browser. I have also found that adding the `--browser-debug` flag after line 14 can be helpful.

If you don't need the HTML pages that singlefile provides and are ok with the JSON data, you can add an early return after line 9 of singlefile.py.

**Comment by jayKlo** [comment]
I was able to get it running on MacOS following @davekats steps. Default chrome path on Mac was "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome". Note that copying the path from Terminal with the escaping backslashes did not work. 

Using the browser-debug flag also seemed to cause it to hang indefinitely at the "Downloading course list page" step and a blank Chrome window remained open, but without that flag it seemed to run fine. 

Thanks for all of your work here, this was a really handy tool.

**Comment by Me-Mr** [comment]
Thank you, I'll try this! Also thanks to @davekats help!

**Comment by davekats** [comment]
Glad to hear you got it running and found the tool helpful @jayKlo!
