### ISSUE TITLE
npm i github command failure

### ISSUE THREAD

**Issue by flamlin** [davekats/canvas-student-data-export#25]
C:\Users\thevi>npm i github:gildas-lormeau/SingleFile
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by davekats** [comment]
Hi @flamlin, it looks like you don't have `git` installed, or it's not in your system's PATH. That will be needed to install SingleFile directly using the `npm i` command.
