### ISSUE TITLE
cannot import name 'Finder' from 'importlib.abc'

### ISSUE THREAD

**Issue by harshitaku** [davekats/canvas-student-data-export#26]
I'm getting this error: 

`line 10, in <module>
    from singlefile import download_page
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/singlefile/__init__.py", line 5, in <module>
    from importlib.abc import Finder, Loader
ImportError: cannot import name 'Finder' from 'importlib.abc' (/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/abc.py)`

**Comment by davekats** [comment]
Hi @harshitaku, can you try using an older version of Python like version 3.8? I suspect 3.12 isn't compatible since it wasn't released when I first developed this tool.

Alternately, if you're willing to submit a PR to enable version compatibility with 3.12 that would be awesome.

**Comment by MatthiasPortzel** [comment]
I'm running in a virtual environment on 3.12 (macOS) with no issue importing, for the record.
```
Python 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from singlefile import download_page
>>>
```

**Comment by davekats** [comment]
@MatthiasPortzel Thank you for looking into this. @harshitaku Can you share more about your runtime environment?
