### ISSUE TITLE
Cannot find module \canvas-student-data-export-master\node_modules\single-file\cli\single-file'

### ISSUE THREAD

**Issue by xenys** [davekats/canvas-student-data-export#28]
code: 'MODULE_NOT_FOUND'
Hello im quite new to coding and im having trouble with this. I installed using npm but the \cli\ folder never appears in my folder?

Is it a version problem of single-file?

THank you in advance :)

**Comment by xenys** [comment]
single-file folder exists but not the subfolder

**Comment by davekats** [comment]
Hi @xenys, this should be fixed in the latest version. Please see https://github.com/davekats/canvas-student-data-export/pull/29 for more details.
