### ISSUE TITLE
Issue with packages (I think)

### ISSUE THREAD

**Issue by nickyg543** [davekats/canvas-student-data-export#8]
Error after running export.py:

Getting list of all courses

  Downloading course list page
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\Nick\ALLCOURSES\node_modules\single-file\cli\single-file'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Having a hard time interpreting this. I have all the packages installed.

**Comment by nickyg543** [comment]
Update: got packages figured out with new error

Failed to launch the browser process! spawn chrome ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md


I'm not sure where to put this chunk of javascript code

**Comment by mjforan** [comment]
Did you set your chrome path in singlefile.py?

**Comment by mjforan** [comment]
BTW there is a typo in singlefile.py which may give you trouble; I am putting together a PR right now to fix that

**Comment by nickyg543** [comment]
I did. It reads:

"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"

For now I will leave the cookies field entry and skip all html-download business.

**Comment by davekats** [comment]
Hi @nickyg543, I'm going to close this but let me know if you still have this issue.
